from enum import Enum
class TokenType(Enum):
    # single-character token types
    DOT         =           "."
    COMMA       =          ","
    SEMICOLON   =    ";"       
    COLON       =         ":"       
    HASHTAG     =     "#"       
    LBRACE      =         "{"           
    RBRACE      =      "}"      
    LPAREN      =      "("     
    RPAREN      =      ")"     
    LBRACKET    =      "["     
    RBRACKET    =       "]"    
    FLOAT_DIV       =          "/"      
    BACK_SLASH  =     "\\"     
    DOUBLE_QUOTE=      "\""    
    SINGLE_QUOTE=      "\'"  
    #Delimiters
    VERTICAL_BAR    = "|"
    UNDERSCORE      = "_"
    #Operational Tokens
    SMALLER         =   "<"
    BIGGER          =   ">"
    EQUAL          =    "="
    NEGATION        =    "!"
    NEGATION_EQUAL  =     "!="
    MOD             =     "%"
    EQUAL_EQUAL     =      "=="
    BIGGER_EQUAL    =      ">="
    SMALLER_EQUAL   =      "<="
    MULT            =       "*"
    PLUS            =      "+"
    MINUS           =      "-"
    POWER           =      "^"

    # block of reserved words
     # marks the beginning of the block
    NUM     =   "NUM"
    NUM_LITERAL = "NUM_LITERAL"
    BOOLEAN_VAR 	=	"BOOL"
    BOOL_LIT = "BOOL_LIT"
    TEXT_VAR 	=	"TEXT"
    TEXT_LITERALS = "TEXT_LITERAL"
    DATE 	=	"DATE"
    DATE_LIT = "DATE_LIT"
    MONEY 	=	"MONEY"
    PHONENUM 	=	"PHONENUM"
    WORDS 	=	"WORDS"
    CHARS 	=	"CHARS"
    SENTENCES 	=	"SENTENCES"
    TEMPLATE 	=	"TEMPLATE"
    ACTIONS 	=	"ACTIONS"
    OPEN 	=	"OPEN"
    INTEGER_DIV   = 'DIV'
    PARAMS 	=	"PARAMS"
    ENUM 	=	"ENUM"
    PACK 	=	"PACK"
    GLOBAL 	=	"GLOBAL"
    CREATE 	=	"CREATE"
    MAKE 	=	"MAKE"
    CONTAINS 	=	"CONTAINS"
    PRINT 	=	"PRINT"
    ERROR 	=	"ERROR"
    INPUT 	=	"INPUT"
    RETURN 	=	"RETURN"
    RIGHT 	=	"RIGHT"
    LEFT 	=	"LEFT"
    MERGE 	=	"MERGE"
    SPLIT 	=	"SPLIT"
    REPLACE 	=	"REPLACE"
    FOR 	=	"FOR"
    UNTIL 	=	"UNTIL"
    DO 	=	"DO"
    IF 	=	"IF"
    ELSE 	=	"ELSE"
    AND 	=	"AND"
    OR 	=	"OR"
    TRUE 	=	"TRUE"
    FALSE 	=	"FALSE"
    NOT 	=	"NOT"
    FONTSIZE 	=	"FONTSIZE"
    FONT 	=	"FONT"
    LENGTH 	=	"LENGTH"
    BEGIN 	=	"BEGIN"
    END 	=	"END"
    DOC 	=	"DOC"
    PDF 	=	"PDF"
    DOCX 	=	"DOCX"
    HTML 	=	"HTML"
    CSV 	=	"CSV"       # marks the end of the block
    #Text tokens
    UNDERLINE 	=	"U"
    ITALIC 	=	"I"
    BOLD 	=	"B"
    IBU   =   "IBU"
    BU     =    "BU"
    IU     =    "IU"
    IB     =    "IB"
    COURIER = "COURIER"
    ARIAL = "ARIAL"
    HELVETICA = "HELVETICA"
    TIMES = "TIMES"
    RESETFONT = "RESETFONT"
    RESETSIZE = "RESETSIZE"
    CENTER 	=	"CENTER"
    LINE 	=	"LINE"
    SPACE 	=	"SPACE"
    TAB 	=	"T"
    PAGE 	=	"PAGE"
    RED 	=	"RED"
    BLUE 	=	"BLUE"
    GREEN 	=	"GREEN"
    MAGENTA 	=	"MAGENTA"
    YELLOW 	=	"YELLOW"
    BROWN 	=	"BROWN"
    GREY 	=	"GREY"
    BLACK 	=	"BLACK"
    IDENTIFIER    = 'IDENTIFIER'
    EOF           = 'EOF'

